#!/bin/bash

# Variables ===================================================================
#
. /usr/local/lib/sahana/edenvars.sh

CONFIG=$EDEN_HOME/models/000_config.py

# Config generation ===========================================================
#
do_generate_nginx_site() {

    SERVERNAME=$1

    cat << EOF > "/etc/nginx/sites-available/$INSTANCE.conf"
server {
    listen      80;
    server_name $SERVERNAME;
    return 301 https://\$server_name\$request_uri;
}
server {
    listen          443 ssl http2;
    server_name     $SERVERNAME;
    ssl_certificate /etc/letsencrypt/live/$SERVERNAME/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/$SERVERNAME/privkey.pem; # managed by Certbot
    ssl_protocols       TLSv1.2;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    location /maintenance.html {
        internal;
        alias /var/www/maintenance.html;
        expires 15s;
    }
    location /crossdomain.xml {
        alias $EDEN_HOME/static/crossdomain.xml;
        expires max;
    }
    location /favicon.ico {
        alias $EDEN_HOME/static/favicon.ico;
        expires 24h;
    }
    location /robots.txt {
        alias $EDEN_HOME/static/robots.txt;
        expires max;
    }
    location /$APPNAME/static/ {
        alias $EDEN_HOME/static/;
        expires 24h;
    }
    location /$APPNAME/static/img/ {
        alias $EDEN_HOME/static/img/;
        gzip off;
        expires 24h;
    }
    # to enable correct use of response.static_version?
    location /static/ {
        alias $EDEN_HOME/static/;
        expires 24h;
    }
    location / {
        error_page 502 = /maintenance.html;
        uwsgi_pass      127.0.0.1:$UWSGI_SOCKET;
        include         /etc/nginx/uwsgi_params;
        uwsgi_param     UWSGI_SCHEME \$scheme;
        uwsgi_param     SERVER_SOFTWARE    nginx/\$nginx_version;
        ### remove the comments if you use uploads (max 30 MB)
        client_max_body_size 30m;
        ###
        port_in_redirect off;
        proxy_redirect off;
    }
}
EOF
}
do_disable_nginx_site() {
    rm -f /etc/nginx/sites-enabled/$INSTANCE.conf
}
do_enable_nginx_site() {
    do_disable_nginx_site
    ln -s /etc/nginx/sites-available/$INSTANCE.conf /etc/nginx/sites-enabled/$INSTANCE.conf
    systemctl restart nginx
}
do_remove_nginx_site() {
    do_disable_nginx_site
    rm -f /etc/nginx/sites-available/$INSTANCE.conf
}

# Server control ==============================================================
#
do_stop_server() {
    systemctl stop uwsgi-$INSTANCE
}
do_start_server() {
    systemctl start uwsgi-$INSTANCE
}
do_open_shell() {
    cd $WEB2PY_HOME
    python web2py.py -S $APPNAME -M
}
do_run_script() {
    cd $WEB2PY_HOME
    sudo -H -u web2py python web2py.py -S $APPNAME -M -R $1
}

# Config edits ================================================================
#
do_enable_migrate() {
    sed -i 's/settings.base.migrate = False/settings.base.migrate = True/g' $CONFIG
}
do_disable_migrate() {
    sed -i 's/settings.base.migrate = True/settings.base.migrate = False/g' $CONFIG
}
do_enable_prepop() {
    sed -i 's/settings.base.prepopulate = 0/#settings.base.prepopulate = 0/g' $CONFIG
}
do_disable_prepop() {
    sed -i 's/#settings.base.prepopulate = 0/settings.base.prepopulate = 0/g' $CONFIG
}
do_set_template() {
    cd $WEB2PY_HOME
    cp $EDEN_HOME/models/000_config.py 000_config.py.bak
    python web2py.py --no_banner -S $APPNAME -R /applications/$APPNAME/static/scripts/tools/set_template.py -A $1 2>&1
    if [ $? -ne 0 ]; then
        cp 000_config.py.bak $EDEN_HOME/models/000_config.py
    fi
}

# Database management =========================================================
#
DBHOST_CONF=/etc/sahana/dbhost.conf
DBHOST=localhost
DBHOST_USER=
DBHOST_KEY=
if [ -f $DBHOST_CONF ]; then
    . $DBHOST_CONF
fi
if [ "$DBHOST" != "localhost" ] && [ "$DBHOST_USER" != "" ] && [ -f $DBHOST_KEY ]; then
    REMOTEDB=0
else
    REMOTEDB=1
fi

do_create_dbuser() {
    if [ $REMOTEDB -eq 0 ]; then
        ssh -i $DBHOST_KEY $DBHOST_USER@$DBHOST /bin/bash << EOF
            sudo su -
            echo "CREATE USER $1 WITH PASSWORD '$2';" > /tmp/pgpass.sql
            su -c - postgres "psql -q -d template1 -f /tmp/pgpass.sql"
            rm -f /tmp/pgpass.sql
EOF
    else
        echo "CREATE USER $1 WITH PASSWORD '$2';" > /tmp/pgpass.sql
        su -c - postgres "psql -q -d template1 -f /tmp/pgpass.sql"
        rm -f /tmp/pgpass.sql
    fi
}
do_drop_dbuser() {
    if [ $REMOTEDB -eq 0 ]; then
        ssh -i $DBHOST_KEY $DBHOST_USER@$DBHOST /bin/bash << EOF
            sudo su -
            su -c - postgres "psql -c 'DROP USER IF EXISTS $DBUSER;'"
EOF
    else
        su -c - postgres "psql -c 'DROP USER IF EXISTS $DBUSER;'"
    fi
}
do_drop_db() {
    if [ $REMOTEDB -eq 0 ]; then
        ssh -i $DBHOST_KEY $DBHOST_USER@$DBHOST /bin/bash << EOF
            sudo su -
            pkill -f "postgres: $DBUSER $DBNAME"
            sudo -H -u postgres dropdb $DBNAME
EOF
    else
        pkill -f "postgres: $DBUSER $DBNAME"
        sudo -H -u postgres dropdb $DBNAME
    fi
}
do_create_db() {
    if [ $REMOTEDB -eq 0 ]; then
        ssh -i $DBHOST_KEY $DBHOST_USER@$DBHOST /bin/bash << EOF
            sudo su -
            su -c - postgres "createdb -O $DBUSER -E UTF8 $DBNAME -T template0"
            su -c - postgres "psql -q -d $DBNAME -c 'CREATE EXTENSION postgis;'"
            su -c - postgres "psql -q -d $DBNAME -c 'GRANT ALL ON geometry_columns TO $DBUSER;'"
            su -c - postgres "psql -q -d $DBNAME -c 'GRANT ALL ON spatial_ref_sys TO $DBUSER;'"
EOF
    else
        su -c - postgres "createdb -O $DBUSER -E UTF8 $DBNAME -T template0"
        su -c - postgres "psql -q -d $DBNAME -c 'CREATE EXTENSION postgis;'"
        su -c - postgres "psql -q -d $DBNAME -c 'GRANT ALL ON geometry_columns TO $DBUSER;'"
        su -c - postgres "psql -q -d $DBNAME -c 'GRANT ALL ON spatial_ref_sys TO $DBUSER;'"
    fi
}
do_check_db_exists() {
    if [ $REMOTEDB -eq 0 ]; then
        ssh -i $DBHOST_KEY $DBHOST_USER@$DBHOST /bin/bash << EOF
            sudo su -
            su -c - postgres "psql -lqt | cut -d \| -f 1 | grep -qw $DBNAME"
EOF
    else
        su -c - postgres "psql -lqt | cut -d \| -f 1 | grep -qw $DBNAME"
    fi
    return $?
}

# Instance Maintenance ========================================================
#
do_compile() {
    cd $WEB2PY_HOME
    do_run_script applications/$APPNAME/static/scripts/tools/compile.py
}
do_noop() {
    cd $WEB2PY_HOME
    do_run_script applications/$APPNAME/static/scripts/tools/noop.py
}
do_pull() {
    do_stop_server

    cd $EDEN_HOME
    git reset --hard HEAD
    git pull
    git submodule update --recursive

    rm -rf $EDEN_HOME/compiled

    do_enable_migrate
    do_noop

    do_disable_migrate
    do_compile

    do_start_server
}
do_migrate() {
    do_stop_server

    rm -rf $EDEN_HOME/compiled

    do_enable_migrate
    do_noop

    do_disable_migrate
    do_compile

    do_start_server
}
do_clean() {
    echo "WARNING: All data from the Eden database will be deleted."
    echo -e "Are you sure? [Type 'clean' to continue] \c"
    read ANSWER

    case $ANSWER in
        clean )
            do_stop_server

            cd $EDEN_HOME
            rm -rf compiled
            rm -rf databases/*
            rm -rf errors/*
            rm -rf sessions/*
            rm -rf uploads/*

            do_drop_db
            do_create_db

            do_enable_migrate
            do_enable_prepop
            do_noop

            do_disable_migrate
            do_disable_prepop
            do_compile

            do_start_server

            if [ -e /home/data/import.py ]; then
                do_run_script /home/data/import.py
            fi
            ;;
        *)
            echo "Aborted."
            return 3
            ;;
    esac
}

# Setup and teardown ==========================================================
#
ask_proceed() {
    echo "$1 (Y)es|(S)kip|e(X)it? [Y]"
    read ANSWER
    case $ANSWER in
        S | s)
            echo "SKIP"
            return 1
            ;;
        X | x)
            echo "EXIT"
            exit 1
            ;;
        *)
            return 0
            ;;
    esac
}
do_setup() {

    echo "Setting up Sahana Eden"

    # Refuse setup if already set up ------------------------------------------
    if do_check_db_exists; then
        echo "ERROR: Database '$DBNAME' exists - aborting."
        return 3
    fi
    if [ -e $EDEN_HOME/databases/*.table ]; then
        echo "ERROR: Table status files found - aborting."
        return 3
    fi
    if [ -e $CONFIG ]; then
        echo "ERROR: Configuration file exists - aborting."
        return 3
    fi

    # Establish the site name (DNS entry must exist) --------------------------
    echo -e "What domain name should we use? : \c "
    read DOMAIN
    echo -e "What host name should we use? : \c "
    read HOSTNAME
    SITENAME=$HOSTNAME".$DOMAIN"

    # Choose a template -------------------------------------------------------
    echo -e "What template should we use? [default] : \c "
    read TEMPLATE
    if [[ ! "$TEMPLATE" ]]; then
        TEMPLATE="default"
    fi

    # Choose a DB password ----------------------------------------------------
    DBPASSWD=`pwgen -1 -A -n 16 -s` # suggest random password
    echo -e "Enter a new database password [$DBPASSWD] \c "
    read password
    if [[ "$password" ]]; then
        DBPASSWD=$password
    fi
    echo "Using $DBPASSWD as database password"

    # Configure Hostname ------------------------------------------------------
    ask_proceed "Configure hostname"
    if [ $? -eq 0 ]; then
        echo -n "Reconfigure system to use the hostname: $HOSTNAME..."
        cd /etc
        filename="hosts"
        sed -i "s|localhost.localdomain localhost|$SITENAME $HOSTNAME localhost.localdomain localhost|" $filename
        filename="hostname"
        echo $HOSTNAME > $filename
        filename="mailname"
        echo $SITENAME > $filename
        echo "Done"
    fi

    # Configure MDA -----------------------------------------------------------
    ask_proceed "Configure MDA"
    if [ $? -eq 0 ]; then
        dpkg-reconfigure "exim4-config"
    fi

    # Configure Certbot -------------------------------------------------------
    ask_proceed "Configure certbot"
    if [ $? -eq 0 ]; then
        # TODO if certbot is not configured, do not configure SSL either
        certbot --nginx
    fi

    # Configure uWSGI ---------------------------------------------------------
    ask_proceed "Configure uWSGI"
    if [ $? -eq 0 ]; then
        # Deploy init script and add systemd service
        cp /usr/local/lib/sahana/uwsgi-$INSTANCE /etc/init.d
        chmod a+x /etc/init.d/uwsgi-$INSTANCE
        update-rc.d uwsgi-$INSTANCE defaults
    fi

    # Configure Nginx ---------------------------------------------------------
    ask_proceed "Configure Nginx"
    if [ $? -eq 0 ]; then
        # Tune nginx parameters
        NGINX_CONF=/etc/nginx/nginx.conf
        sed -i "s|# gzip_vary on;|gzip_vary on;|" $NGINX_CONF
        sed -i "s|# gzip_proxied any;|gzip_proxied expired no-cache no-store private auth;|" $NGINX_CONF
        sed -i "s|# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;|gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;|" $NGINX_CONF
        sed -i "/.*gzimp_min_length.*/d" $NGINX_CONF
        sed -i "/gzip_vary on;/a gzip_min_length 10240;" $NGINX_CONF
        sed -i "s|gzip_min_length|\tgzip_min_length|" $NGINX_CONF

        # Disable default site
        rm -f /etc/nginx/sites-enabled/default

        # Generate and enable site for instance
        do_generate_nginx_site $SITENAME
        do_enable_nginx_site
    fi

    # Configure Eden ----------------------------------------------------------
    ask_proceed "Configure Eden"
    if [ $? -eq 0 ]; then
        echo -n "Create config file from template..."
        rm -rf $EDEN_HOME/compiled
        rm -rf $EDEN_HOME/databases/*
        rm -rf $EDEN_HOME/sessions/*
        rm -rf $EDEN_HOME/errors/*
        rm -rf $EDEN_HOME/uploads/*
        rm -f $CONFIG
        cp $EDEN_HOME/modules/templates/000_config.py $EDEN_HOME/models

        do_set_template "$TEMPLATE"
        sed -i 's|EDITING_CONFIG_FILE = False|EDITING_CONFIG_FILE = True|' $CONFIG

        # Create a unique HMAC key for password encryption
        UUID=`python -c $'import uuid\nprint(uuid.uuid4())'`
        sed -i "s|akeytochange|$UUID|" $CONFIG
        sed -i "s|#settings.base.public_url = \"http://127.0.0.1:8000\"|settings.base.public_url = \"https://$SITENAME\"|" $CONFIG
        sed -i 's|#settings.base.cdn = True|settings.base.cdn = True|' $CONFIG
        echo "Done"
    fi

    # Configure Database ------------------------------------------------------
    ask_proceed "Configure Database"
    if [ $? -eq 0 ]; then
        do_create_dbuser $DBUSER $DBPASSWD
        do_create_db
        echo -n "Update Eden config for database..."
        sed -i 's|#settings.database.db_type = "postgres"|settings.database.db_type = "postgres"|' $CONFIG
        if [ $REMOTEDB -eq 0 ]; then
            sed -i "s|#settings.database.host = \"localhost\"|settings.database.host = \"$DBHOST\"|" $CONFIG
        fi
        sed -i "s|#settings.database.password = \"password\"|settings.database.password = \"$DBPASSWD\"|" $CONFIG
        sed -i 's|#settings.gis.spatialdb = True|settings.gis.spatialdb = True|' $CONFIG
        echo "Done"
    fi

    # TODO Configure backup

    # 1st run -----------------------------------------------------------------
    ask_proceed "First run"
    if [ $? -eq 0 ]; then

        do_enable_prepop
        do_enable_migrate
        do_noop

        do_disable_migrate
        do_disable_prepop
        do_compile
    fi
}
do_teardown() {

    echo "WARNING: The Eden database and instance configuration will be deleted."
    echo -e "Are you sure? [Type 'teardown' to continue] \c"
    read ANSWER
    case $ANSWER in
        teardown)
            do_stop_server

            # Drop UWSGI init script and remove service
            echo "Removing uWSGI service"
            rm -f /etc/init.d/uwsgi-$INSTANCE
            update-rc.d -f uwsgi-$INSTANCE remove

            # Drop Nginx site
            echo "Removing Nginx site configuration"
            rm -f /etc/nginx/sites-enabled/$INSTANCE.conf
            rm -f /etc/nginx/sites-available/$INSTANCE.conf
            systemctl reload nginx

            # Drop eden database and DB user
            echo "Removing database and DB user"
            do_drop_db
            do_drop_dbuser

            # Remove all table files, errors, sessions, and uploads
            echo "Removing files"
            rm -rf $EDEN_HOME/compiled
            rm -rf $EDEN_HOME/databases/*
            rm -rf $EDEN_HOME/sessions/*
            rm -rf $EDEN_HOME/errors/*
            rm -rf $EDEN_HOME/uploads/*

            # Remove 000_config.py file
            echo "Removing Eden configuration file"
            rm -f $CONFIG

            # TODO remove backup configuration

            return 0
            ;;
        *)
            return 3
            ;;
    esac
}

# Dispatch ====================================================================
#
case "$1" in
    start)
        do_start_server
        ;;
    stop)
        do_stop_server
        ;;
    shell)
        do_open_shell
        ;;
    run)
        do_run_script $2
        ;;
    setup)
        do_setup
        ;;
    template)
        do_set_template $2
        ;;
    teardown)
        do_teardown
        ;;
    pull)
        do_pull
        ;;
    migrate)
        do_migrate
        ;;
    compile)
        do_compile
        ;;
    clean)
        do_clean
        ;;
    *)
        echo "edenctl error: unknown command $1"
        echo "Usage: edenctl {start|stop|shell|run|pull|migrate|compile|clean}" >&2
        exit 3
        ;;
esac

:
